# Generated by Django 3.1.6 on 2021-02-23 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasker', '0002_auto_20210223_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='self', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='task name', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.ManyToManyField(null=True, related_name='_task_subtasks_+', to='tasker.Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='target_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='target_date'),
        ),
        migrations.AddField(
            model_name='task',
            name='taskers',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
