# Generated by Django 3.1.6 on 2021-02-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0003_auto_20210223_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_date',
            field=models.DateTimeField(null=True, verbose_name='target_date'),
        ),
    ]
