# Generated by Django 3.1.6 on 2021-02-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0004_auto_20210223_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='subtasks',
            field=models.ManyToManyField(related_name='_task_subtasks_+', to='tasker.Task'),
        ),
    ]
