# Generated by Django 3.1.6 on 2021-02-23 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasker', '0005_auto_20210223_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='taskers',
        ),
        migrations.AddField(
            model_name='task',
            name='taskers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
