# Generated by Django 3.1.6 on 2021-02-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0006_auto_20210223_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='has_end',
            field=models.BooleanField(default=False),
        ),
    ]
