# Generated by Django 3.1.6 on 2021-02-23 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasker', '0007_task_has_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskers',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
