# Generated by Django 3.1.6 on 2021-02-23 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasker', '0008_auto_20210223_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='has_end',
        ),
        migrations.AlterField(
            model_name='task',
            name='subtasks',
            field=models.ManyToManyField(blank=True, related_name='_task_subtasks_+', to='tasker.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='target_date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
