# Generated by Django 3.1.6 on 2021-02-24 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasker', '0009_auto_20210223_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskers',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
