# Generated by Django 3.1.6 on 2021-02-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0010_auto_20210224_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
