# Generated by Django 3.1.6 on 2021-02-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0012_auto_20210224_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subtasks',
        ),
        migrations.RemoveField(
            model_name='task',
            name='taskers',
        ),
    ]
