# Generated by Django 3.1.6 on 2021-02-27 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0018_auto_20210225_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='level',
        ),
        migrations.RemoveField(
            model_name='task',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='task',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasker.task'),
        ),
    ]
