# Generated by Django 3.1.6 on 2021-03-10 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker_frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(default=None, max_length=200, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='log',
            name='name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
