# Generated by Django 3.1.6 on 2021-03-10 15:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasker_frontend', '0002_auto_20210310_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tasker_frontend.company'),
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 23, 7, 56, 242144)),
        ),
        migrations.AddField(
            model_name='log',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='log',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tasker_frontend.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 23, 7, 56, 226516)),
        ),
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
