# Generated by Django 3.1.6 on 2021-03-13 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker_frontend', '0010_auto_20210313_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 21, 33, 48, 141907)),
        ),
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 21, 33, 48, 141907)),
        ),
    ]
