# Generated by Django 3.1.6 on 2021-03-13 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker_frontend', '0012_auto_20210313_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 22, 5, 36, 996606)),
        ),
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 22, 5, 36, 996606)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('C2C', 'COMPANY_TO_COMPANY'), ('C2D', 'COMPANY_TO_DEPARTMENT'), ('D2D', 'DEPARTMENT_TO_DEPARTMENT'), ('D2U', 'DEPARTMENT_TO_USER'), ('U2D', 'USER_TO_DEPARTMENT'), ('U2U', 'USER_TO_USER')], max_length=200),
        ),
    ]
