# Generated by Django 3.1.6 on 2021-03-13 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker_frontend', '0014_auto_20210313_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 22, 11, 51, 321463)),
        ),
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 22, 11, 51, 321463)),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
