# Generated by Django 3.1.6 on 2021-03-30 07:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasker_frontend', '0021_auto_20210324_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=500)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2021, 3, 30, 15, 21, 11, 482922))),
                ('members', models.ManyToManyField(blank=True, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=500)),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tasker_frontend.project')),
            ],
        ),
        migrations.CreateModel(
            name='TaskListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=500)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2021, 3, 30, 15, 21, 11, 488911))),
                ('due_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('assingned_to', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('parent_list', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tasker_frontend.tasklist')),
            ],
        ),
        migrations.RemoveField(
            model_name='department',
            name='company',
        ),
        migrations.RemoveField(
            model_name='task',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='task',
            name='taskers',
        ),
        migrations.RemoveField(
            model_name='log',
            name='task',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.AlterField(
            model_name='log',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 15, 21, 11, 492907)),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='log',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tasker_frontend.project'),
        ),
    ]
