# Generated by Django 3.1.6 on 2021-03-30 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker_frontend', '0022_auto_20210330_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklistitem',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 15, 28, 26, 204473)),
        ),
        migrations.AlterField(
            model_name='project',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 15, 28, 26, 179519)),
        ),
        migrations.AlterField(
            model_name='tasklistitem',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 15, 28, 26, 186503)),
        ),
    ]
