# Generated by Django 3.1.6 on 2021-03-30 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker_frontend', '0023_auto_20210330_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 23, 4, 12, 952455)),
        ),
        migrations.AlterField(
            model_name='project',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 23, 4, 12, 942471)),
        ),
        migrations.AlterField(
            model_name='tasklistitem',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 23, 4, 12, 948462)),
        ),
    ]
